import matplotlib.pyplot as plt

BLOCK_SIZE = 4
KEY_SIZE = 5  # Maximum key size
ROUNDS = 2
KEYS_PER_SECOND = 10
# -*- coding: utf-8 -*-
"""Excersie2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYUACfJXmrZWai2f2Hjb_oBGHb0bWjn0
"""



block= int(input("Enter a 4-bit block, e.g., 1110 ") ,2)
key= int(input("Enter up to a 5-bit key, e.g., 10111 ") ,2)

# Initial Values for the Encryption and Decryption


# Substitution-Box Function
def substitution_box(cipher, key):
    return (5* block +(key & 0b1111)) % 16 #This ensures that only the last 4 bits of the key is used.

# Inverse Substitution
def inverse_substitution_box(chiper):
    return (13*(chiper-(key & 0b1111))) % 16 # Reverses the Substitution-Box Transformation

# XOR Function
def XOR(block, key):
  return key ^ block

#Permutation Function

def permutation(block):
    return (((block & 0b1000) >> 3) |  # Move bit 3 to bit 0
            ((block & 0b0100) >> 1) |  # Move bit 2 to bit 1
            ((block & 0b0010) << 1) |  # Move bit 1 to bit 2
            ((block & 0b0001) << 3))   # Move bit 0 to bit 3

#def permutation(block):
  #return ((block & 0b10000 >> 3)) | (block & 0b01000) | ((block & 0b00100)>> 2) |((block & 0b00010) << 1) | ((block & 0b00001)<<4) # Reorders the bits

#Inverse Permutation
def inverse_permutation(block):
    return (((block & 0b1000) >> 3) |  # Move bit 3 to bit 0
            ((block & 0b0100) >> 1) |  # Move bit 2 to bit 1
            ((block & 0b0010) << 1) |  # Move bit 1 to bit 2
            ((block & 0b0001) << 3))   # Move bit 0 to bit 3


#def inverse_permutation(block):
  #return ((block & 0b10000)>>4) | (block & 0b01000) | ((block & 0b00100)>>1) | ((block & 0b00010)<< 3) | ((block & 0b00001)<<2) #Reverses the permutation function

# Encryption Scheme

def encrypt(rounds=2):
    print(block)
    print("\n.....Starting Encryption.....")
    encrypted = block
    for i in range (rounds):
        if i ==0:
            substitute = substitution_box(encrypted, key)
            print("s_box:", substitute)
            encrypted = XOR(substitute, key)
            print("xor_1:", bin(encrypted))
        else:
            permute = inverse_permutation(encrypted)
            print("permute:", permute)
            encrypted = XOR(permute, key)
            print("xor_2:", encrypted)

    b_left, b_right = block >> 2, block & 0b11
    result = (b_right << 5) | encrypted
    return result

# Decryption Scheme

def decrypt(encrypted):
    print("\n......Starting Decryption......")
    
    permute = XOR(encrypted, key)
    print("xor_2:", bin(permute))

    permute_inverse = inverse_permutation(permute)
    print("permute_inverse:", bin(permute_inverse))

    s_box = XOR(permute_inverse, key)
    print("xor_1:", bin(s_box))

    result = inverse_substitution_box(s_box)
    return result

    #b_right, cipher = (encrypted >> 5), encrypted & 0b11111
    #print("b_right: ", bin(b_right), "xor_2: ", cipher)
    #permute = XOR(cipher, key)
    #print("permute: ", permute)
    #permute_inverse = permutation(permute)
    #print("xor_1: ", permute_inverse)
    #s_box = XOR(permute_inverse, key)
    #print("s_box: ", s_box)
    #result =  inverse_substitution_box(s_box)
    #return result

# Excute's the Encryption and Decryption

encrypted_value=encrypt()
print("\nEncrypted:", bin(encrypted_value))

decrypted_value=decrypt(encrypted_value)
print("\nDecrypted:", bin(decrypted_value))


# Brute-Force Attack Analysis
def brute_force_attack(ciphertext, block_size, keys_per_second=KEYS_PER_SECOND):
    results = {}
    for key_length in range(1, KEY_SIZE + 1):  # Iterate up to the maximum key size
        attempts = 2**key_length
        time_seconds = attempts / keys_per_second

        # Store results more concisely
        results[key_length] = time_seconds

    return results

brute_force_results = brute_force_attack(encrypted_value, BLOCK_SIZE)

# Plotting (more efficient and readable)
key_lengths = list(brute_force_results.keys())
times = list(brute_force_results.values())

plt.figure(figsize=(10, 6))
plt.plot(key_lengths, times, marker='o')
plt.xlabel("Key Length (bits)")
plt.ylabel("Time (seconds) (log scale)") #Y label more descriptive
plt.title("Brute-Force Attack Time")
plt.grid(True)
plt.xticks(key_lengths)
plt.yscale('log')  # Log scale for y-axis
plt.tight_layout()
plt.show()

# print("\nBrute-force attack complexities and times (assuming 10 keys tested per second):")
# for k, t in brute_force_results.items():
#     attempts = 2**k
#     minutes = t / 60
#     hours = minutes / 60
#     days = hours / 24
#     print(f"Key length {k}: 2^{k} = {attempts} attempts")
#     print(f"Time: {t:.2f} seconds, {minutes:.2f} minutes, {hours:.2f} hours, {days:.2f} days")
#     print("-" * 50)