# -*- coding: utf-8 -*-
"""Excersie2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYUACfJXmrZWai2f2Hjb_oBGHb0bWjn0
"""

#block = 0b1110
#key = 0b10111

block= int(input("Enter a 4-bit block, e.g., 1110 ") ,2)
key= int(input("Enter up to a 5-bit key, e.g., 10111 ") ,2)

# Initial Values for the Encryption and Decryption

block= 0b1110 #4-bit binary represntation of 14
key = 0b1011  #5-bit key representation of 23

# Substitution-Box Function
def substitution_box(cipher, key):
    return (5* block +(key & 0b1111)) % 16 #This ensures that only the last 4 bits of the key is used.

# Inverse Substitution
def inverse_substitution_box(chiper):
    return (13*(chiper-(key & 0b1111))) % 16 # Reverses the Substitution-Box Transformation

# XOR Function
def XOR(block, key):
  return key ^ block

#Permutation Function

def permutation(block):
    return (((block & 0b1000) >> 3) |  # Move bit 3 to bit 0
            ((block & 0b0100) >> 1) |  # Move bit 2 to bit 1
            ((block & 0b0010) << 1) |  # Move bit 1 to bit 2
            ((block & 0b0001) << 3))   # Move bit 0 to bit 3

#def permutation(block):
  #return ((block & 0b10000 >> 3)) | (block & 0b01000) | ((block & 0b00100)>> 2) |((block & 0b00010) << 1) | ((block & 0b00001)<<4) # Reorders the bits

#Inverse Permutation
def inverse_permutation(block):
    return (((block & 0b1000) >> 3) |  # Move bit 3 to bit 0
            ((block & 0b0100) >> 1) |  # Move bit 2 to bit 1
            ((block & 0b0010) << 1) |  # Move bit 1 to bit 2
            ((block & 0b0001) << 3))   # Move bit 0 to bit 3


#def inverse_permutation(block):
  #return ((block & 0b10000)>>4) | (block & 0b01000) | ((block & 0b00100)>>1) | ((block & 0b00010)<< 3) | ((block & 0b00001)<<2) #Reverses the permutation function

# Encryption Scheme

def encrypt(rounds=2):
    print(block)
    print("\n.....Starting Encryption.....")
    encrypted = block
    for i in range (rounds):
        if i ==0:
            substitute = substitution_box(encrypted, key)
            print("s_box:", substitute)
            encrypted = XOR(substitute, key)
            print("xor_1:", bin(encrypted))
        else:
            permute = inverse_permutation(encrypted)
            print("permute:", permute)
            encrypted = XOR(permute, key)
            print("xor_2:", encrypted)

    b_left, b_right = block >> 2, block & 0b11
    result = (b_right << 5) | encrypted
    return result

# Decryption Scheme

def decrypt(encrypted):
    print("\n......Starting Decryption......")

    permute = XOR(encrypted, key)
    print("xor_2:", bin(permute))

    permute_inverse = inverse_permutation(permute)
    print("permute_inverse:", bin(permute_inverse))

    s_box = XOR(permute_inverse, key)
    print("xor_1:", bin(s_box))

    result = inverse_substitution_box(s_box)
    return result

    #b_right, cipher = (encrypted >> 5), encrypted & 0b11111
    #print("b_right: ", bin(b_right), "xor_2: ", cipher)
    #permute = XOR(cipher, key)
    #print("permute: ", permute)
    #permute_inverse = permutation(permute)
    #print("xor_1: ", permute_inverse)
    #s_box = XOR(permute_inverse, key)
    #print("s_box: ", s_box)
    #result =  inverse_substitution_box(s_box)
    #return result

# Excute's the Encryption and Decryption

encrypted_value=encrypt()
print("\nEncrypted:", bin(encrypted_value))

decrypted_value=decrypt(encrypted_value)
print("\nDecrypted:", bin(decrypted_value))

import matplotlib.pyplot as plt

def brute_force_time(key_length, keys_per_second=10):
    """
    Calculate the brute force time in seconds, minutes, hours, and days
    for a given key length assuming an attacker can test `keys_per_second` per second.
    """
    # Calculate the total number of possible keys
    keys_to_test = 2 ** key_length

    # Calculate time in seconds
    time_seconds = keys_to_test / keys_per_second

    # Convert time into minutes, hours, and days
    time_minutes = time_seconds / 60
    time_hours = time_minutes / 60
    time_days = time_hours / 24

    return time_seconds, time_minutes, time_hours, time_days

# Function to test different key lengths (from 1 to 5 bits)
def test_brute_force_times():
    key_lengths = range(1, 6)  # Key lengths from 1 to 5
    results = {}

    for key_length in key_lengths:
        time_seconds, time_minutes, time_hours, time_days = brute_force_time(key_length)
        results[key_length] = {
            'seconds': time_seconds,
            'minutes': time_minutes,
            'hours': time_hours,
            'days': time_days
        }

    return results

# Function to plot brute force times
def plot_brute_force_times(results):
    key_lengths = list(results.keys())
    time_seconds = [results[key]['seconds'] for key in key_lengths]
    time_minutes = [results[key]['minutes'] for key in key_lengths]
    time_hours = [results[key]['hours'] for key in key_lengths]
    time_days = [results[key]['days'] for key in key_lengths]

    # Create subplots for each unit of time
    fig, axs = plt.subplots(2, 2, figsize=(10, 8))

    axs[0, 0].plot(key_lengths, time_seconds, label='Seconds')
    axs[0, 0].set_title('Time in Seconds')
    axs[0, 0].set_xlabel('Key Length (bits)')
    axs[0, 0].set_ylabel('Time (seconds)')

    axs[0, 1].plot(key_lengths, time_minutes, label='Minutes')
    axs[0, 1].set_title('Time in Minutes')
    axs[0, 1].set_xlabel('Key Length (bits)')
    axs[0, 1].set_ylabel('Time (minutes)')

    axs[1, 0].plot(key_lengths, time_hours, label='Hours')
    axs[1, 0].set_title('Time in Hours')
    axs[1, 0].set_xlabel('Key Length (bits)')
    axs[1, 0].set_ylabel('Time (hours)')

    axs[1, 1].plot(key_lengths, time_days, label='Days')
    axs[1, 1].set_title('Time in Days')
    axs[1, 1].set_xlabel('Key Length (bits)')
    axs[1, 1].set_ylabel('Time (days)')

    # Show the plot
    plt.tight_layout()
    plt.show()

# Main code to calculate and plot brute force times
results = test_brute_force_times()

# Print out the brute force time for each key length
for key_length, time_info in results.items():
    print(f"Key Length: {key_length} bits")
    print(f"  Time in seconds: {time_info['seconds']:.2f} seconds")
    print(f"  Time in minutes: {time_info['minutes']:.2f} minutes")
    print(f"  Time in hours: {time_info['hours']:.2f} hours")
    print(f"  Time in days: {time_info['days']:.2f} days")
    print()

# Plot the results
plot_brute_force_times(results)