import matplotlib.pyplot as plt

# -*- coding: utf-8 -*-
"""Excersie2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYUACfJXmrZWai2f2Hjb_oBGHb0bWjn0
"""

#block = 0b1110
#key = 0b10111

block= int(input("Enter a 4-bit block, e.g., 1110 ") ,2)
key= int(input("Enter up to a 5-bit key, e.g., 10111 ") ,2)

# Initial Values for the Encryption and Decryption

block= 0b1110 #4-bit binary represntation of 14
key = 0b1011  #5-bit key representation of 23

# Substitution-Box Function
def substitution_box(cipher, key):
    return (5* block +(key & 0b1111)) % 16 #This ensures that only the last 4 bits of the key is used.

# Inverse Substitution
def inverse_substitution_box(chiper):
    return (13*(chiper-(key & 0b1111))) % 16 # Reverses the Substitution-Box Transformation

# XOR Function
def XOR(block, key):
  return key ^ block

#Permutation Function

def permutation(block):
    return (((block & 0b1000) >> 3) |  # Move bit 3 to bit 0
            ((block & 0b0100) >> 1) |  # Move bit 2 to bit 1
            ((block & 0b0010) << 1) |  # Move bit 1 to bit 2
            ((block & 0b0001) << 3))   # Move bit 0 to bit 3

#def permutation(block):
  #return ((block & 0b10000 >> 3)) | (block & 0b01000) | ((block & 0b00100)>> 2) |((block & 0b00010) << 1) | ((block & 0b00001)<<4) # Reorders the bits

#Inverse Permutation
def inverse_permutation(block):
    return (((block & 0b1000) >> 3) |  # Move bit 3 to bit 0
            ((block & 0b0100) >> 1) |  # Move bit 2 to bit 1
            ((block & 0b0010) << 1) |  # Move bit 1 to bit 2
            ((block & 0b0001) << 3))   # Move bit 0 to bit 3


#def inverse_permutation(block):
  #return ((block & 0b10000)>>4) | (block & 0b01000) | ((block & 0b00100)>>1) | ((block & 0b00010)<< 3) | ((block & 0b00001)<<2) #Reverses the permutation function

# Encryption Scheme

def encrypt(rounds=2):
    print(block)
    print("\n.....Starting Encryption.....")
    encrypted = block
    for i in range (rounds):
        if i ==0:
            substitute = substitution_box(encrypted, key)
            print("s_box:", substitute)
            encrypted = XOR(substitute, key)
            print("xor_1:", bin(encrypted))
        else:
            permute = inverse_permutation(encrypted)
            print("permute:", permute)
            encrypted = XOR(permute, key)
            print("xor_2:", encrypted)

    b_left, b_right = block >> 2, block & 0b11
    result = (b_right << 5) | encrypted
    return result

# Decryption Scheme

def decrypt(encrypted):
    print("\n......Starting Decryption......")

    permute = XOR(encrypted, key)
    print("xor_2:", bin(permute))

    permute_inverse = inverse_permutation(permute)
    print("permute_inverse:", bin(permute_inverse))

    s_box = XOR(permute_inverse, key)
    print("xor_1:", bin(s_box))

    result = inverse_substitution_box(s_box)
    return result

    #b_right, cipher = (encrypted >> 5), encrypted & 0b11111
    #print("b_right: ", bin(b_right), "xor_2: ", cipher)
    #permute = XOR(cipher, key)
    #print("permute: ", permute)
    #permute_inverse = permutation(permute)
    #print("xor_1: ", permute_inverse)
    #s_box = XOR(permute_inverse, key)
    #print("s_box: ", s_box)
    #result =  inverse_substitution_box(s_box)
    #return result

# Excute's the Encryption and Decryption

encrypted_value=encrypt()
print("\nEncrypted:", bin(encrypted_value))

decrypted_value=decrypt(encrypted_value)
print("\nDecrypted:", bin(decrypted_value))




def brute_force_attack(ciphertext, block_size, keys_per_second=10):
    results = {}
    for key_length in range(1, 6):  # Test keys from 1 to 5 bits
        attempts = 2 ** key_length
        time_seconds = attempts / keys_per_second

        # Convert time to other units
        time_minutes = time_seconds / 60
        time_hours = time_minutes / 60
        time_days = time_hours / 24

        results[key_length] = {
            "attempts": attempts,
            "seconds": time_seconds,
            "minutes": time_minutes,
            "hours": time_hours,
            "days": time_days
        }
    return results


# ... (Example usage and ciphertext_example from previous response) ...

brute_force_results = brute_force_attack(encrypted_value, 4)

key_lengths = list(brute_force_results.keys())
attempts = [brute_force_results[k]["attempts"] for k in key_lengths]
seconds = [brute_force_results[k]["seconds"] for k in key_lengths]
minutes = [brute_force_results[k]["minutes"] for k in key_lengths]
hours = [brute_force_results[k]["hours"] for k in key_lengths]
days = [brute_force_results[k]["days"] for k in key_lengths]

plt.figure(figsize=(10, 6))  # Adjust figure size for better readability

plt.subplot(2, 2, 1)  # 2 rows, 2 columns, first plot
plt.plot(key_lengths, attempts, marker='o')
plt.xlabel("Key Length (bits)")
plt.ylabel("Number of Attempts (2^n)")
plt.title("Brute-Force Attempts")
plt.grid(True)
plt.xticks(key_lengths)
plt.yscale('log')

plt.subplot(2, 2, 2)  # 2 rows, 2 columns, second plot
plt.plot(key_lengths, seconds, marker='o')
plt.xlabel("Key Length (bits)")
plt.ylabel("Time (seconds)")
plt.title("Brute-Force Time (seconds)")
plt.grid(True)
plt.xticks(key_lengths)
plt.yscale('log')

plt.subplot(2, 2, 3)  # 2 rows, 2 columns, third plot
plt.plot(key_lengths, minutes, marker='o')
plt.xlabel("Key Length (bits)")
plt.ylabel("Time (minutes)")
plt.title("Brute-Force Time (minutes)")
plt.grid(True)
plt.xticks(key_lengths)
plt.yscale('log')

plt.subplot(2, 2, 4)  # 2 rows, 2 columns, fourth plot
plt.plot(key_lengths, days, marker='o')
plt.xlabel("Key Length (bits)")
plt.ylabel("Time (days)")
plt.title("Brute-Force Time (days)")
plt.grid(True)
plt.xticks(key_lengths)
plt.yscale('log')

plt.tight_layout()  # Adjust subplot params so that subplots fit in to the figure area.
plt.show()

print("Brute-force attack complexities and times (assuming 10 keys tested per second):")
for k, v in brute_force_results.items():
    print(f"Key length {k}: 2^{k} = {v['attempts']} attempts")
    print(f"Time: {v['seconds']:.2f} seconds, {v['minutes']:.2f} minutes, {v['hours']:.2f} hours, {v['days']:.2f} days")
    print("-" * 50)  # Separator for clarity